apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  egress:
  - {}
  ingress:
  - {}
  podSelector:
    matchLabels:
      {{- include "mlflow.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
